version: '3'
services:
  node:
    build: .
    command: npm start
    ports:
      - "5555:5000"
    env_file:
      - .env.prod
    depends_on:
      - redis
    links:
      - redis
    restart: always
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:
