version: '3'
services:
  node:
    build: .
    command: npm run dev
    volumes:
      - ./:/usr/app
    ports:
      - 5000:5000
      # node debugger port
      - 9229::9229
    env_file:
      - .env
    depends_on:
      - redis
    links:
      - redis
  redis:
    ports:
      - 6379:6379
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
